#数据源配置
server: 
   port: 8081
spring: 
   datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://127.0.0.1:3306/sql_injection?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
      username: root
      password: rx123456
      driver-class-name: com.mysql.cj.jdbc.Driver
      dpcp2.max-idle: 10
      dbcp2.max-wait-millis: 10000
      dbcp2.min-idle: 5
      dbcp2.initial-size: 5
#mybatis-plus配置
mybatis-plus: 
   dialect: mysql
   mapper-locations: classpath:/mapper/*Mapper.xml
   typeAliasesPackage: com.jsql.model.bean
   global-config: 
      db-config: 
         id-type: uuid
#解决，查询返回结果含null,Map没有对应字段值问题 # 配置slq打印日志
   configuration: 
      call-setters-on-nulls: true
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
html: 
   location: /Users/renxiao/desktop
